### ISSUE TITLE
Unable to find Pod

### ISSUE THREAD

**Issue by imanfkl** [ImanX/zarainpal-ios-payment#4]
<img width="866" alt="screen shot 2018-07-02 at 12 56 45" src="https://user-images.githubusercontent.com/11244707/42162724-bd6ae3da-7df7-11e8-8ae9-21550ba1a1de.png">

Unable to find a specification for 'ZarinPalSDKPayment'

**Comment by ImanX** [comment]
@imanfkl Please update your pod and try it.
